package com.example.wavehome

object Maps {}

val deviceVariables = mapOf(
    "AC_UNIT" to listOf("fanSpeed", "isOn", "targetTemperature", "currentTemperature"),
    "AIRCOOLER" to listOf("fanSpeed", "isOn", "targetTemperature", "currentTemperature", "targetHumidity", "currentHumidity"),
    "AIRFRESHENER" to listOf("isOn", "mode", "toggleState"),
    "AIRPURIFIER" to listOf("isOn", "fanSpeed", "airQuality", "filterLife"),
    "AUDIO_VIDEO_RECEIVER" to listOf("inputSource", "mediaState", "isOn", "transportState", "volumeLevel", "selectedApp"),
    "AWNING" to listOf("isOpen"),
    "BATHTUB" to listOf("isOpen", "fillLevel", "targetTemperature", "currentTemperature", "isRunning"),
    "BED" to listOf("mode", "scene"),
    "BLANKET" to listOf("isOn", "mode", "toggleState", "targetTemperature"),
    "BLENDER" to listOf("isOn", "cookMode", "isRunning", "timerRemaining"),
    "BLINDS" to listOf("isOpen", "rotationAngle"),
    "BOILER" to listOf("isOn", "targetTemperature", "currentTemperature"),
    "CAMERA" to listOf("isStreaming", "motionDetected"),
    "CARBON_MONOXIDE_DETECTOR" to listOf("coLevel", "coDetected"),
    "CHARGER" to listOf("batteryLevel", "chargeCapacity"),
    "CLOSET" to listOf("isOpen"),
    "COFFEE_MAKER" to listOf("isOn", "cookMode", "targetTemperature"),
    "COOKTOP" to listOf("isOn", "cookMode", "timerRemaining"),
    "CURTAIN" to listOf("isOpen"),
    "DEHUMIDIFIER" to listOf("isOn", "fanSpeed", "targetHumidity", "currentHumidity", "isRunning"),
    "DEHYDRATOR" to listOf("isOn", "cookMode", "isRunning", "timerRemaining"),
    "DISHWASHER" to listOf("isRunning", "cycleState", "isOn"),
    "DOOR" to listOf("isOpen", "isLocked"),
    "DOORBELL" to listOf("motionDetected", "isStreaming"),
    "DRAWER" to listOf("isOpen"),
    "DRYER" to listOf("isRunning", "cycleState", "mode", "toggleState", "isOn"),
    "FAN" to listOf("fanSpeed", "isOn"),
    "FAUCET" to listOf("isRunning", "dispenseAmount", "targetTemperature", "currentTemperature"),
    "FIREPLACE" to listOf("isOn", "mode", "toggleState"),
    "FREEZER" to listOf("targetTemperature", "currentTemperature"),
    "FRYER" to listOf("isOn", "cookMode", "isRunning", "timerRemaining"),
    "GAME_CONSOLE" to listOf("isOn", "selectedApp", "mediaState", "inputSource", "volumeLevel", "transportState"),
    "GARAGE" to listOf("isOpen", "isLocked"),
    "GATE" to listOf("isOpen", "isLocked"),
    "GRILL" to listOf("isRunning", "cookMode", "timerRemaining", "isOn"),
    "HEATER" to listOf("fanSpeed", "targetTemperature", "currentTemperature"),
    "HOOD" to listOf("isOn", "fanSpeed", "brightnessLevel"),
    "HUMIDIFIER" to listOf("isOn", "fanSpeed", "targetHumidity", "currentHumidity", "isRunning"),
    "KETTLE" to listOf("isOn", "targetTemperature", "currentTemperature"),
    "LIGHT" to listOf("isOn", "brightnessLevel", "colorValue"),
    "LOCK" to listOf("isLocked"),
    "MICROWAVE" to listOf("isRunning", "cookMode", "timerRemaining"),
    "MOP" to listOf("isRunning", "cycleState", "batteryLevel", "isDocked", "location", "isOn"),
    "MOWER" to listOf("isRunning", "cycleState", "batteryLevel", "isDocked", "location", "isOn"),
    "MULTICOOKER" to listOf("isOn", "cookMode", "isRunning", "timerRemaining"),
    "NETWORK" to listOf("networkStatus", "qosMode", "guestNetworkEnabled"),
    "OUTLET" to listOf("isOn"),
    "OVEN" to listOf("isOn", "cookMode", "targetTemperature", "currentTemperature", "timerRemaining"),
    "PERGOLA" to listOf("isOpen", "rotationAngle"),
    "PETFEEDER" to listOf("dispenseAmount", "isOn", "isRunning"),
    "PRESSURECOOKER" to listOf("isOn", "cookMode", "timerRemaining"),
    "PUMP" to listOf("isOn"),
    "RADIATOR" to listOf("isOn", "mode", "toggleState"),
    "REFRIGERATOR" to listOf("targetTemperature", "currentTemperature"),
    "REMOTECONTROL" to listOf("isOn", "inputSource", "mediaState", "selectedApp", "channel", "volumeLevel", "transportState"),
    "ROUTER" to listOf("networkStatus", "qosMode", "guestNetworkEnabled"),
    "SCENE" to listOf("sceneState"),
    "SECURITYSYSTEM" to listOf("armState", "securityStatus"),
    "SENSOR" to listOf("sensorValue", "batteryLevel"),
    "SETTOP" to listOf("isOn", "selectedApp", "mediaState", "channel", "volumeLevel", "transportState"),
    "SHOWER" to listOf("isRunning", "targetTemperature", "currentTemperature"),
    "SHUTTER" to listOf("isOpen", "rotationAngle"),
    "SMOKE_DETECTOR" to listOf("smokeLevel", "smokeDetected"),
    "SOUNDBAR" to listOf("isOn", "mediaState", "inputSource", "volumeLevel", "transportState", "selectedApp"),
    "SOUSVIDE" to listOf("isOn", "cookMode", "isRunning", "timerRemaining"),
    "SPEAKER" to listOf("isOn", "mediaState", "inputSource", "volumeLevel", "transportState", "selectedApp"),
    "SPRINKLER" to listOf("isRunning", "timerRemaining"),
    "STANDMIXER" to listOf("isOn", "cookMode", "isRunning"),
    "STREAMING_BOX" to listOf("isOn", "selectedApp", "mediaState", "channel", "inputSource", "volumeLevel", "transportState"),
    "STREAMING_SOUNDBAR" to listOf("isOn", "mediaState", "inputSource", "volumeLevel", "transportState", "selectedApp"),
    "STREAMING_STICK" to listOf("isOn", "mediaState", "volumeLevel", "transportState", "selectedApp"),
    "SWITCH" to listOf("isOn", "brightnessLevel"),
    "THERMOSTAT" to listOf("targetTemperature", "currentTemperature", "thermostatMode"),
    "TV" to listOf("isOn", "selectedApp", "inputSource", "mediaState", "channel", "volumeLevel", "transportState"),
    "VACUUM" to listOf("isRunning", "cycleState", "batteryLevel", "isDocked", "location", "isOn"),
    "VALVE" to listOf("isOpen"),
    "WASHER" to listOf("isRunning", "cycleState", "mode", "toggleState", "isOn"),
    "WATERHEATER" to listOf("isOn", "targetTemperature", "currentTemperature"),
    "WATERPURIFIER" to listOf("isOn", "waterQuality", "filterLife"),
    "WATERSOFTENER" to listOf("isOn", "waterQuality", "filterLife"),
    "WINDOW" to listOf("isOpen", "isLocked"),
    "YOGURTMAKER" to listOf("isOn", "cookMode", "isRunning", "timerRemaining")
)
